-- ================================================================
-- ⚠️  ARCHIVO DEPRECADO — NO APLICAR
-- ================================================================
--
-- Este archivo contiene las políticas RLS originales (pre-multi-tenant).
-- Las políticas que define NO incluyen filtro por organization_id,
-- por lo que si se re-aplican cualquier usuario autenticado puede
-- leer y escribir datos de CUALQUIER organización en la plataforma.
--
-- FUENTE DE VERDAD ACTUAL:
--   prisma/migrations/20260618000000_add_org_id_to_all_tables/migration.sql
--
-- Esa migración reemplaza TODAS las políticas de este archivo por
-- versiones multi-tenant que usan auth_org_id() para aislar datos
-- entre organizaciones.
--
-- Si necesitás consultar las políticas activas en la DB:
--   SELECT schemaname, tablename, policyname, cmd, qual
--   FROM pg_policies
--   WHERE schemaname = 'public'
--   ORDER BY tablename, policyname;
--
-- Si necesitás replicar la configuración completa en una DB nueva,
-- ejecutar las migraciones de Prisma en orden:
--   npx prisma migrate deploy
--
-- ================================================================
-- El contenido original se preserva en el historial de git:
--   git log --follow supabase/rls_policies.sql
--   git show HEAD~1:supabase/rls_policies.sql
-- ================================================================
